# fly launch --image ghcr.io/aerofeev/sap-bin-parser:latest --copy-config
app = "sap-bin"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  path = "/healthz"
  interval = "30s"
  timeout = "5s"

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"
